server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
#  cloud:
#    gateway:
#      routes:
#        - id: USER-SERVICE
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/auth/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: USER-SERVICE
#                fallbackuri: forward:/userServiceFallBack
#        - id: CORE-SERVICE
#          uri: lb://CORE-SERVICE
#          predicates:
#            - Path=/core/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: CORE-SERVICE
#                fallbackuri: forward:/coreServiceFallBack


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

